spring:
  main:
    banner-mode: "off"
  batch:
    schema: classpath:sql/schema-@@platform@@.sql
    table-prefix: REFUND_MASS_LOADER_BATCH_

feign:
  refund:
    # URL of the refund management service
    url: ${service.refund:http://localhost:8085/v1/refunds}