###
#   Server Settings
###
server:
  port: 8080

###
#   Application Settings
###
spring:
  application:
    name: @projectName@
       
  ###
  #   Database Settings
  ###
  datasource:
    url: jdbc:h2:mem:testdb
    platform: h2
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true
        ddl-auto: none  
        
  ###
  #   H2 Settings
  ###
  h2:
    console:
      enabled: true
  
  ###
  #  Flyway Settings
  ###
  flyway:
    enabled: true
    locations: classpath:/db/migration,/db/data/dev 

###
#   Logging Settings
###
logging:
  file: ${spring.application.name}.json.log
  level:
    org:
      hibernate:
        type: trace
  