spring:
  flyway:
    enabled: true
    locations: classpath:/db/migration,/db/data/dev
  jpa:
    generate-ddl: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        ddl-auto: none
        default_schema: filemanagement
  h2:
    console:
      enabled: true
logging:
  level:
    org:
      hibernate:
        type: trace
app:
  yade:
    save_in_bbdd_and_user_outbox_enable: false
    inbox: /data/nfe/jobscheduler_inbox
    outbox: /data/nfe/jobscheduler_outbox
    host:
      sftp:
        name: 10.5.0.40
        user: jobsch
        password: Scheduler.18
        directory: /data/nfe/jobscheduler_inbox
        protocol: sftp
        port: 22
      local:
        name: localhost
        user: 
        password: 
        directory: /data/nfe/jobscheduler_outbox
        protocol: local
        port:

keycloak:
  auth-server-url: http://keycloak-dev.nfedev.accelya.com/auth
  realm: NFE
  public-client: true
  resource: bsplink-file-manager
  principal-attribute: preferred_username        