spring:
  flyway:
    schemas: filemanagement
  devtools:
    restart:
      exclude: files/**
  servlet:
    multipart:
      max-file-size: 2MB
  jpa:
    properties:
      hibernate:
        format_sql: true
        ddl-auto: none
        default_schema: filemanagement
        temp:
          use_jdbc_metadata_defaults: false
app:
  file_name_rex: ^([A-Z]{2})([a-z0-9]{2})([^_]+)_.*$
  file_name_outbox_replacement: $3/$1/outbox/$2/
  file_name_eliminated_replacement: $3/$1/outbox/$2/eliminated
  file_name_type_replacement: $2
  local_uploaded_files_directory: uploaded_files
  local_downloaded_files_directory: downloaded_files
  zip:
    name: test.zip
  yade:
    save_in_bbdd_and_user_outbox_enable: false
    inbox: /data/nfe/jobscheduler_inbox
    outbox: /data/nfe/jobscheduler_outbox
    host:
      sftp:
        name: sftp
        user: jobsch
        password: 
        directory: 
        protocol: sftp
        port: 22
      local:
        name: localhost
        user: 
        password: 
        directory: 
        protocol: local
        port: 
        
keycloak:
  auth-server-url: 
  realm: 
  resource: 
  bearer-only: true
  
###
#  Feign clients
###
feign:
  users:
    url: http://localhost:8085/v1/users