spring:
      
  flyway:
    locations: classpath:/db/migration,/db/data/dev 

  jpa:
    generate-ddl: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        ddl-auto: none

  h2:
    console:
      enabled: true

logging:
  level:
    org:
      hibernate:
        type: trace
app:
  yade:
    save_in_bbdd_and_user_outbox_enable: false
    inbox: /data/nfe/jobscheduler_inbox
    outbox: /data/nfe/jobscheduler_outbox
    host:
      sftp:
        name: sftp.nfedev.accelya.com
        user: sftpuatadmin
        password: Adm1n
        directory: /data/nfe/jobscheduler_inbox
        protocol: sftp
        port: 2225
      local:
        name: localhost
        user: 
        password: 
        directory: /data/nfe/jobscheduler_outbox
        protocol: local
        port:
        