###
#   Server Settings
###
server:
  port: 8080

###
#   Application Settings
###
spring:
  application:
    name: bsplink-refund-management
       
  ###
  #   Database Settings
  ###
  datasource:
    url: jdbc:h2:mem:refund
    platform: h2
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true
        ddl-auto: none 
        default_schema: refund
        
  ###
  #   H2 Settings
  ###
  h2:
    console:
      enabled: true
  
  ###
  #  Flyway Settings
  ###
  flyway:
    enabled: true
    locations: classpath:/db/migration,/db/data/dev
    schemas: refund

###
#   Logging Settings
###
logging:
  file: ${spring.application.name}.json.log
  level:
    org:
      hibernate:
        type: trace

###
#   App Settings
###
app:
  local_attached_files_directory: attached_files
  remote_full_path_file: attached_files/%s/refund/%d/%s
  remote_attached_files_directory: attached_files/%s/refund/%d
  host:  
    sftp:      
      name: sftp.nfedev.accelya.com
      username: sftpadmin
      password: 
      port: 2225
      protocol: sftp
    local:
      name: localhost
      username:
      password:
      port:
      protocol: local
  