feign:
  agents:
    url: http://localhost:8082/v1/agents
  airlines:
    url: http://localhost:8083/v1/airlines
spring:
  jpa:
    properties:
      hibernate:
        default_schema: bsplink_user
        
keycloak:
  auth-server-url: http://keycloak-dev.nfedev.accelya.com/auth
  realm: NFE
  resource: bsplink-user-management
  bearer-only: true
  
keycloak-admin:
  master-realm:
  admin-username:
  admin-pass:
  admin-client-id: