spring:
  jpa:
    properties:
      hibernate:
        temp:
          # Gets rid of PostgreSql's related exception:
          # Disabling contextual LOB creation as createClob() method threw error
          use_jdbc_metadata_defaults: false
        default_schema: airlinemanagement
  flyway:
    schemas: airlinemanagement

keycloak:
  auth-server-url: http://keycloak-dev.nfedev.accelya.com/auth
  realm: NFE
  public-client: true
  resource: bsplink-airline-management
  bearer-only: true