spring:
      
  flyway:
    locations: classpath:/db/migration,/db/data/dev 

  jpa:
    generate-ddl: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        ddl-auto: none

  h2:
    console:
      enabled: true

logging:
  level:
    org:
      hibernate:
        type: trace

keycloak:
  auth-server-url: http://keycloak-dev.nfedev.accelya.com/auth
  realm: NFE
  public-client: true
  resource: bsplink-airline-management
  principal-attribute: preferred_username         