
DROP TABLE  IF EXISTS REFUND_MASS_LOADER_BATCH_STEP_EXECUTION_CONTEXT;
DROP TABLE  IF EXISTS REFUND_MASS_LOADER_BATCH_JOB_EXECUTION_CONTEXT;
DROP TABLE  IF EXISTS REFUND_MASS_LOADER_BATCH_STEP_EXECUTION;
DROP TABLE  IF EXISTS REFUND_MASS_LOADER_BATCH_JOB_EXECUTION_PARAMS;
DROP TABLE  IF EXISTS REFUND_MASS_LOADER_BATCH_JOB_EXECUTION;
DROP TABLE  IF EXISTS REFUND_MASS_LOADER_BATCH_JOB_INSTANCE;

DROP SEQUENCE  IF EXISTS REFUND_MASS_LOADER_BATCH_STEP_EXECUTION_SEQ ;
DROP SEQUENCE  IF EXISTS REFUND_MASS_LOADER_BATCH_JOB_EXECUTION_SEQ ;
DROP SEQUENCE  IF EXISTS REFUND_MASS_LOADER_BATCH_JOB_SEQ ;
