spring:
      
  flyway:
    locations: classpath:/db/migration,/db/data/dev 

  jpa:
    generate-ddl: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        ddl-auto: none

  h2:
    console:
      enabled: true

logging:
  level:
    org:
      hibernate:
        type: trace

app:
  local_attached_files_directory: attached_files
  remote_full_path_file: attached_files/%s/acdm/%d/%s
  remote_attached_files_directory: attached_files/%s/acdm/%d  
  file_name_rex: ^([A-Z]{2})([a-z0-9]{2})([^_]+)_.*$
  host:  
    sftp:      
      name: 10.5.0.40
      username: jobsch
      password:
      port: 22
      protocol: sftp
    local:
      name: localhost
      username:
      password:
      port:
      protocol: local
      
keycloak:
  auth-server-url: http://keycloak-dev.nfedev.accelya.com/auth
  realm: NFE
  public-client: true
  resource: bsplink-agency-memo
  bearer-only: true       