#!/usr/bin/env groovy

env.sourceBranch = env.gitlabSourceBranch ?: 'develop'
env.gitlabRepositoryUrl = env.gitlabSourceRepoHttpUrl ?: 'http://gitlab.nfedev.accelya.com/bsplink/nfe-frontend.git'

echo "[INFO] Source Branch: ${env.sourceBranch}"
echo "[INFO] Source Repository URL: ${env.gitlabRepositoryUrl}"

// add source branch to description ss
def sourceBranch = "Source Branch: " + env.sourceBranch
currentBuild.description = currentBuild.description ? currentBuild.description + "\n${sourceBranch}" : sourceBranch

pipeline {

    agent {
        label 'master'
    }

    stages {

         
        stage('Push to IATA Develop_repository') {
            steps {
            	// this shell script is located in <JENKINS_HOME>/bin folder and the PATH is configured through jenkins
                sh 'push_to_iata2.bash $WORKSPACE $JOB_BASE_NAME'
			}
        }



  	}
}
