#!/usr/bin/env groovy

env.sourceBranch = env.gitlabSourceBranch ?: 'develop'
env.gitlabRepositoryUrl = env.gitlabSourceRepoHttpUrl ?: 'http://gitlab.nfedev.accelya.com/bsplink/nfe-frontend.git'

echo "[INFO] Source Branch: ${env.sourceBranch}"
echo "[INFO] Source Repository URL: ${env.gitlabRepositoryUrl}"

// add source branch to description
def sourceBranch = "Source Branch: " + env.sourceBranch
currentBuild.description = currentBuild.description ? currentBuild.description + "\n${sourceBranch}" : sourceBranch

pipeline {

    agent {
        label 'master'
    }

    stages {

        stage('Build') {
            steps {
                checkout poll: false, scm: [
					$class: 'GitSCM',
					branches: [[name: "*/${env.sourceBranch}" ]],
					doGenerateSubmoduleConfigurations: false,
						extensions: [],
						submoduleCfg: [],
						userRemoteConfigs: [[
							credentialsId: env.gitlabCredentialsId,
							url: "${env.gitlabRepositoryUrl}"
					]]]
				nodejs('nodejs') {
				    sh 'npm install'
                    sh 'npm run build'
                }
                dir('dist') {
                    stash name: 'nfe-frontend-artifact'
                }
            }
        }

         stage('Test') {
            steps {
                nodejs('nodejs') {
                    sh 'npm run test'
                   // sh 'npm run e2e'
                }
			}
        }

        stage('SonarQube') {
            steps {
                configFileProvider([configFile(fileId: 'sonar-project.properties', targetLocation: '.')]) {
                    script {
                        def scannerHome = tool 'sonarscanner3.2.0';
                        withSonarQubeEnv('a2lsonarq1') {
                            sh "${scannerHome}/bin/sonar-scanner"
                        }
                    }
                }
	        }
	  	}

        stage('Nexus') {
            steps {
            	// sh 'npm login --registry=http://nexusinterno.nfedev.accelya.com/repository/nfe-frontend/'
                sh 'npm publish --registry=http://nexusinterno.nfedev.accelya.com/repository/nfe-frontend/'
	        }
	  	}

        stage('Push to IATA repository') {
			/*
        when{
          expression{
            return env.sourceBranch == 'master'
          }
  			}
        */
            steps {
            	// this shell script is located in <JENKINS_HOME>/bin folder and the PATH is configured through jenkins
                //sh 'push_to_iata.bash $WORKSPACE $JOB_BASE_NAME'
                sh 'push_to_iata2.bash $WORKSPACE $JOB_BASE_NAME'
			}
        }

        stage('Deploy') {
            agent {
                label 'a2lyadesch1'
            }
            steps {
                dir('dist') {
                    unstash 'nfe-frontend-artifact'
                }
                sh './deploy-docker.sh'
			}
        }
  	}
}
